In [1]:
import vhe
import numpy as np
HE = vhe.HE()
x = np.arange(10).astype(object)

In [2]:
T = HE.TGen(10)
S = HE.getSecretkey(T)

In [3]:
c = HE.encrypt(T=T,x=x)

In [4]:
c1 = c*2
HE.decrypt(S=S,c=c1)

array([0, 2, 4, 6, 8, 10, 12, 14, 16, 18], dtype=object)

In [14]:
G=np.random.rand(10,10)
c2 = HE.linearTransform(HE.linearTransformClient(G,S,T),c)
output1=HE.decrypt(S=S,c=c2)
output2=G.dot(x)
print(output2-output1)

[-0.49702134220979843 -0.004150460914226883 0.34248065328616306
 -0.3446315080647864 0.2899133514134036 0.46607300546373054
 0.2267998373217246 -0.11115423404439895 -0.011432169607690668
 -0.09181479508070467]


In [16]:
G1=np.random.rand(120,10)
G2=np.random.rand(10,120)
T120=HE.TGen(120)
S120=HE.getSecretkey(T120)
c2 = HE.linearTransform(HE.linearTransformClient(G1,S,T120),c)
c2 = HE.linearTransform(HE.linearTransformClient(G2,S120,T),c2)
output1=HE.decrypt(S=S,c=c2)
output2=G1.dot(x)
output2=G2.dot(output2)
print(output2-output1)

[0.15041905249017873 -0.1350898623638841 -0.15127925560341282
 -0.34215050253169466 -0.2370981107251282 -0.2741594183594316
 -0.28771507320470846 -0.29448101674370264 -0.39156906725543195
 -0.26201164063331817]


In [7]:
W = np.zeros(1000,dtype=object).reshape(10,10,10)
for i in range(10):
    W[i,i,i] = 1
c4 = HE.innerProd(c,c,HE.WeightedInnerProdClient(W,T))
HE.decrypt(S=S,c=c4)

array([0, 1, 4, 9, 16, 25, 36, 49, 64, 81], dtype=object)

In [8]:
G2 = np.zeros((20,10))
for i in range(10):
    G2[2*i:2*i+2,i] = 1
T_new = HE.TGen(20)
S_new = HE.getSecretkey(T_new)
c5 = HE.linearTransform(HE.linearTransformClient(G2,S,T_new),c)
HE.decrypt(S=S_new,c=c5)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9],
      dtype=object)

In [9]:
G3 = np.zeros((5,10))
for i in range(5):
    G3[i,2*i] = 1
T3 = HE.TGen(5)
S3 = HE.getSecretkey(T3)
c6 = HE.linearTransform(HE.linearTransformClient(G3,S,T3),c)
HE.decrypt(S=S3,c=c6)

array([0, 2, 4, 6, 8], dtype=object)